# Generated by Django 5.1.2 on 2024-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_master', '0002_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='character_icons/'),
        ),
    ]
