# Generated by Django 5.1.2 on 2025-03-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_master', '0003_alter_character_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
