# Generated by Django 5.1.2 on 2025-03-12 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', '月曜日'), ('TUE', '火曜日'), ('WED', '水曜日'), ('THU', '木曜日'), ('FRI', '金曜日')], max_length=3)),
                ('period', models.IntegerField(choices=[(1, '1限'), (2, '2限'), (3, '3限'), (4, '4限'), (5, '5限'), (6, '6限')])),
                ('subject_name', models.CharField(max_length=100)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day', 'period'],
                'unique_together': {('user', 'day', 'period')},
            },
        ),
    ]
